// Code generated by qtc from "maxlen.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line goqtpl/maxlen.qtpl:1
package goqtpl

//line goqtpl/maxlen.qtpl:1
import "github.com/unsafe-risk/go-alrescha/parser"

//line goqtpl/maxlen.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line goqtpl/maxlen.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line goqtpl/maxlen.qtpl:3
func StreamMaxLenConst(qw422016 *qt422016.Writer, max parser.MaxLen) {
//line goqtpl/maxlen.qtpl:3
	qw422016.N().S(`
const (
    ALRESCHA_MAX_STRING_SIZE = `)
//line goqtpl/maxlen.qtpl:5
	qw422016.N().D(max.StringMaxLen)
//line goqtpl/maxlen.qtpl:5
	qw422016.N().S(`
    ALRESCHA_MAX_BYTES_SIZE  = `)
//line goqtpl/maxlen.qtpl:6
	qw422016.N().D(max.BytesMaxLen)
//line goqtpl/maxlen.qtpl:6
	qw422016.N().S(`
    ALRESCHA_MAX_LISTS_ITEM = `)
//line goqtpl/maxlen.qtpl:7
	qw422016.N().D(max.ListMaxItem)
//line goqtpl/maxlen.qtpl:7
	qw422016.N().S(`
)
var _ = ALRESCHA_MAX_STRING_SIZE
var _ = ALRESCHA_MAX_BYTES_SIZE
var _ = ALRESCHA_MAX_LISTS_ITEM

var ErrSizeExceeded error = fmt.Errorf("field size exceeds maximum size")
var _ = ErrSizeExceeded
`)
//line goqtpl/maxlen.qtpl:15
}

//line goqtpl/maxlen.qtpl:15
func WriteMaxLenConst(qq422016 qtio422016.Writer, max parser.MaxLen) {
//line goqtpl/maxlen.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line goqtpl/maxlen.qtpl:15
	StreamMaxLenConst(qw422016, max)
//line goqtpl/maxlen.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line goqtpl/maxlen.qtpl:15
}

//line goqtpl/maxlen.qtpl:15
func MaxLenConst(max parser.MaxLen) string {
//line goqtpl/maxlen.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line goqtpl/maxlen.qtpl:15
	WriteMaxLenConst(qb422016, max)
//line goqtpl/maxlen.qtpl:15
	qs422016 := string(qb422016.B)
//line goqtpl/maxlen.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line goqtpl/maxlen.qtpl:15
	return qs422016
//line goqtpl/maxlen.qtpl:15
}
