// Code generated by qtc from "struct.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/struct.qtpl:1
package templates

//line templates/struct.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/struct.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/struct.qtpl:2
type StructField struct {
	Name string
	Type string
}

//line templates/struct.qtpl:8
func StreamGenerateStruct(qw422016 *qt422016.Writer, name string, fields []StructField) {
//line templates/struct.qtpl:8
	qw422016.N().S(`
type `)
//line templates/struct.qtpl:9
	qw422016.E().S(name)
//line templates/struct.qtpl:9
	qw422016.N().S(` struct {
`)
//line templates/struct.qtpl:10
	for _, field := range fields {
//line templates/struct.qtpl:10
		qw422016.N().S(`
    `)
//line templates/struct.qtpl:11
		qw422016.E().S(field.Name)
//line templates/struct.qtpl:11
		qw422016.N().S(` `)
//line templates/struct.qtpl:11
		qw422016.E().S(field.Type)
//line templates/struct.qtpl:11
		qw422016.N().S(`
`)
//line templates/struct.qtpl:12
	}
//line templates/struct.qtpl:12
	qw422016.N().S(`
}
`)
//line templates/struct.qtpl:14
	for _, field := range fields {
//line templates/struct.qtpl:14
		qw422016.N().S(`
func (v *`)
//line templates/struct.qtpl:15
		qw422016.E().S(name)
//line templates/struct.qtpl:15
		qw422016.N().S(`) Get`)
//line templates/struct.qtpl:15
		qw422016.E().S(field.Name)
//line templates/struct.qtpl:15
		qw422016.N().S(`() `)
//line templates/struct.qtpl:15
		qw422016.E().S(field.Type)
//line templates/struct.qtpl:15
		qw422016.N().S(` {
    return v.`)
//line templates/struct.qtpl:16
		qw422016.E().S(field.Name)
//line templates/struct.qtpl:16
		qw422016.N().S(`
}

func (v *`)
//line templates/struct.qtpl:19
		qw422016.E().S(name)
//line templates/struct.qtpl:19
		qw422016.N().S(`) Set`)
//line templates/struct.qtpl:19
		qw422016.E().S(field.Name)
//line templates/struct.qtpl:19
		qw422016.N().S(`(value `)
//line templates/struct.qtpl:19
		qw422016.E().S(field.Type)
//line templates/struct.qtpl:19
		qw422016.N().S(`) {
    v.`)
//line templates/struct.qtpl:20
		qw422016.E().S(field.Name)
//line templates/struct.qtpl:20
		qw422016.N().S(` = value
}
`)
//line templates/struct.qtpl:22
	}
//line templates/struct.qtpl:22
	qw422016.N().S(`
`)
//line templates/struct.qtpl:23
}

//line templates/struct.qtpl:23
func WriteGenerateStruct(qq422016 qtio422016.Writer, name string, fields []StructField) {
//line templates/struct.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/struct.qtpl:23
	StreamGenerateStruct(qw422016, name, fields)
//line templates/struct.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line templates/struct.qtpl:23
}

//line templates/struct.qtpl:23
func GenerateStruct(name string, fields []StructField) string {
//line templates/struct.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/struct.qtpl:23
	WriteGenerateStruct(qb422016, name, fields)
//line templates/struct.qtpl:23
	qs422016 := string(qb422016.B)
//line templates/struct.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/struct.qtpl:23
	return qs422016
//line templates/struct.qtpl:23
}
